### PR TITLE
Visualization updated, minor fixes.

### PR DESCRIPTION
**Pull request by obsh**

### CODE REVIEW

**Comment by Firedrops** [comment]
Why was CPU target utilization changed from 0.5 to 0.1? Is it more stable that way? more nodes with less load on each to reduce chance of freezing?

**Comment by Firedrops** [comment]
Noticed that the provisioner will spin up many VMs and max out quota for a few minutes, leading to this error when deploying dataflow:

```
 2019-02-20 (15:57:10) Workflow failed. Causes: Project nano-stream1 has insufficient quota(s) to execute this workflow wit...
Workflow failed. Causes: Project nano-stream1 has insufficient quota(s) to execute this workflow with 1 instances in region asia-northeast1. Quota summary (required/available): 1/236 instances, 4/0 CPUs, 430/3696 disk GB, 0/500 SSD disk GB, 1/99 instance groups, 1/49 managed instance groups, 1/98 instance templates, 1/5 in-use IP addresses.

Please see https://cloud.google.com/compute/docs/resource-quotas about requesting more quota.
```

It resolves itself after a while, the provisioner eventually goes back to 1 VM.

**Comment by Firedrops** [comment]
@obsh sorry just tagging you again, worried this will just get lost in the email spam and you won't see it in issues.

**Comment by obsh** [comment]
No problem, I've really lost this one.
Yes, the default value of this parameter were changed to stimulate auto-scaling when CPU load is not that high.
Aligner VMs are memory intensive not CPU, and we observed out of memory errors while VM was trying to serve 4-5 simultaneous requests.

**Comment by obsh** [comment]
Regarding quota, you can request change:
https://console.cloud.google.com/iam-admin/quotas

**Comment by Firedrops** [comment]
We have requested additional quota but it seems to take a while to process. Should we switch cpu type to `highmem`? [CPU types](https://cloud.google.com/compute/docs/machine-types). 4 seems like a good place to start to find a good compromise between RAM and higher CPU usage.

**Comment by obsh** [comment]
Switching to `highmem` machines is a good idea, I believe. I'll test this configuration. 
Also I'm going to test different disk options, as disk performance probably has big impact on aligner in it's current setup.

**Pull request merged**
